objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_ins__Availability__c</fullName>
        <label>Availability</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__MarketSegment__c</fullName>
        <label>Market Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ASO (Admin Services Only)</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Mid Sized Group</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__ProviderNetworkId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Network</label>
        <referenceTo>vlocity_ins__ProviderNetwork__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__StandardPremium__c</fullName>
        <label>Standard Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__SubType__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_ins__Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>HDHP</fullName>
                </value>
                <value>
                    <fullName>Indemnity</fullName>
                </value>
                <value>
                    <fullName>FSA</fullName>
                </value>
                <value>
                    <fullName>HSA</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>PCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Medical Savings Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_ins__ProviderNetworkId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Network</label>
        <referenceTo>vlocity_ins__ProviderNetwork__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>QuoteLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__Type__c</fullName>
        <formula>Text(Product2.vlocity_ins__Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_ins__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>vlocity_ins__AttributeCategoryId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute Category copied from the attribute at the time the attribute was assigned.</description>
        <label>Attribute Category</label>
        <referenceTo>vlocity_ins__AttributeCategory__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__DisplaySequence__c</fullName>
        <description>Category display sequence copied from the attribute category at the time the attribute was assigned.</description>
        <label>Category Display Sequence</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ObjectId__c</fullName>
        <description>ID of the parent object to which the attribute is assigned.</description>
        <externalId>true</externalId>
        <label>Assigned To Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ValueDataType__c</fullName>
        <label>Value Data Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ValueDescription__c</fullName>
        <description>Description of the value assigned to this attribute.</description>
        <label>Value Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__Value__c</fullName>
        <description>Value of this attribute. For example, attribute strength (0-5), or a text value &quot;Jimmy&quot;.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_ins__AttributeCategory__c.object
<CustomObject>
    <description>Vlocity Attribute Categories allow Attributes to be assigned to admin-defined groupings. The Category also identifies some characteristics of the profiling attributes in that grouping.</description>
    <fields>
        <fullName>vlocity_ins__DisplaySequence__c</fullName>
        <description>Display sequence of this category in the profile details section.</description>
        <label>Display Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Vlocity Attribute Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attribute Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_ins__ContractLineItem__c.object
<CustomObject>
    <description>A health insurance plan or retirement plan established by an employer or an employee organization (such as a union) to offer insurance or retirement services to its members.  Plans are governed by a contract, offered by an insurance or retirement services provider and administered by plan administrators.</description>
    <fields>
        <fullName>vlocity_ins__Availability__c</fullName>
        <formula>vlocity_ins__ContractId__r.Account.BillingState</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Availability</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ContractId__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>ContractLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracted Plans</relationshipLabel>
        <relationshipName>OrderProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED. Use Product2Id__c instead.</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Benefit Plans</relationshipLabel>
        <relationshipName>GroupBenefitsPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_ins__ProductRelationship__c.object
<CustomObject>
    <description>Represents relationships between two insurance products and their child components which defines the optional coverage specifications for a policy.</description>
    <fields>
        <fullName>vlocity_ins__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the subject product for which this relationship is defined. For an &quot;Excludes&quot; relationship, this identifies the product that excludes another product. For a &quot;Relies On&quot; relationship, this identifies the product which has a dependency on another product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Relationships</relationshipLabel>
        <relationshipName>RelatedProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__RelatedProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the product related to the subject product in this relationship. For an &quot;Excludes&quot; relationship, this identifies a product excluded by the subject product. For a &quot;Relies On&quot; relationship, this identifies the product that can fulfill the dependency of the subject product.</description>
        <label>Related Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Relationships</relationshipLabel>
        <relationshipName>ProductRelations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Relationship</label>
    <nameField>
        <label>Product Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/INS_GetProducts.cls
global with sharing class INS_GetProducts implements vlocity_ins.VlocityOpenInterface{
    
    public Map<Id, Product2> productMap = new Map<Id, Product2>();

    public Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean success = true;

        try{
            if(methodName == 'getProducts') {
                getProducts(inputMap, outMap, options);
            }
        }catch(Exception e){
            System.debug(' exception '+e.getStackTraceString());
            System.debug(' exception '+e);
            success = false;
            throw e;
        }
        
        return success;
    }
    public void getProducts(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options){
            
            String searchPlanType = (String) inputMap.get('PlanType');
            String searchPlanDescription = (String) inputMap.get('PlanDescription');
            String outputPlanType = (String) inputMap.get('PlanType') + 'Plans'; 
            String targetSource = (String) inputMap.get('targetSource'); 
            
            system.debug(targetSource);
            productMap = new Map<Id, Product2>();
            if(targetSource == 'Renewals'){
                List<vlocity_ins__ContractLineItem__c> ContractLineItemList = [Select Id, vlocity_ins__ProductId__c, vlocity_ins__ProductId__r.Name, vlocity_ins__ProductId__r.vlocity_ins__Type__c, vlocity_ins__ProductId__r.vlocity_ins__EffectiveDate__c, vlocity_ins__ProductId__r.ProductCode from vlocity_ins__ContractLineItem__c where vlocity_ins__ContractId__c =:(String)inputMap.get('ContextId') AND vlocity_ins__ProductId__r.vlocity_ins__Type__c =:searchPlanType ];
                system.debug(ContractLineItemList);
                
                Set<Id> SourceProductIds = new Set<Id>();
                for(vlocity_ins__ContractLineItem__c contract: ContractLineItemList){
                    SourceProductIds.add(contract.vlocity_ins__ProductId__c);
                    
                    Product2 prod = new Product2(Id=contract.vlocity_ins__ProductId__c, Name=contract.vlocity_ins__ProductId__r.Name, vlocity_ins__Type__c=contract.vlocity_ins__ProductId__r.vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c=contract.vlocity_ins__ProductId__r.vlocity_ins__EffectiveDate__c, ProductCode=contract.vlocity_ins__ProductId__r.ProductCode, vlocity_ins__StandardPremium__c=null);
                    productMap.put(contract.vlocity_ins__ProductId__c, prod);

                }
                system.debug(SourceProductIds);
                List<vlocity_ins__ProductRelationship__c> ProductList = [Select vlocity_ins__RelatedProductId__c, vlocity_ins__RelatedProductId__r.ProductCode, vlocity_ins__RelatedProductId__r.Name, vlocity_ins__RelatedProductId__r.vlocity_ins__StandardPremium__c, vlocity_ins__RelatedProductId__r.vlocity_ins__EffectiveDate__c, vlocity_ins__RelatedProductId__r.vlocity_ins__Type__c FROM vlocity_ins__ProductRelationship__c where vlocity_ins__Product2Id__c IN :SourceProductIds];
                system.debug(ProductList);
                
                for(vlocity_ins__ProductRelationship__c p:ProductList){
                    Product2 prod = new Product2(Id=p.vlocity_ins__RelatedProductId__c, Name=p.vlocity_ins__RelatedProductId__r.Name, vlocity_ins__Type__c=p.vlocity_ins__RelatedProductId__r.vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c=p.vlocity_ins__RelatedProductId__r.vlocity_ins__EffectiveDate__c, ProductCode=p.vlocity_ins__RelatedProductId__r.ProductCode, vlocity_ins__StandardPremium__c=null);
                    productMap.put(p.vlocity_ins__RelatedProductId__c, prod);
                }
            }
            else if(targetSource == 'Enrollment'){
                List<QuoteLineItem> QuoteLineItemList = [Select Id, Product2.Name, Product2.ProductCode, Product2.vlocity_ins__EffectiveDate__c, Product2.vlocity_ins__Type__c, Product2Id, UnitPrice from QuoteLineItem where QuoteId =:(String)inputMap.get('ContextId') AND Product2.vlocity_ins__Type__c =:searchPlanType ];
                
                Map<Id, QuoteLineItem> contractMap = new Map<Id, QuoteLineItem>();
                system.debug(QuoteLineItemList);
                for(QuoteLineItem p:QuoteLineItemList){
                    Product2 prod = new Product2(Id=p.Product2Id, Name=p.Product2.Name, vlocity_ins__Type__c=p.Product2.vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c=p.Product2.vlocity_ins__EffectiveDate__c, ProductCode=p.Product2.ProductCode, vlocity_ins__StandardPremium__c=p.UnitPrice);
                    productMap.put(p.Product2Id, prod);
                }
            }
            else if(targetSource == 'Medicare'){
                String State = (String)inputMap.get('State');
                Map<String, Object> constructEffectiveDate = (Map<String,Object>) inputMap.get('plansPage');
                productMap = new Map<Id, Product2>([SELECT Id, ProductCode, Name, vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c, vlocity_ins__StandardPremium__c from Product2 WHERE vlocity_ins__StandardPremium__c != null AND vlocity_ins__Type__c =:searchPlanType AND vlocity_ins__MarketSegment__c = 'Medicare' AND (NOT Name LIKE '%Group%') AND vlocity_ins__Availability__c includes (:State) LIMIT 5000]);
            }
            else if(targetSource == 'MedicarePlan'){
                Map<String, Object> SelectProductCategory = (Map<String,Object>) inputMap.get('SelectProductCategory');
                system.debug(SelectProductCategory);
                List<Object> SIProductCategories = (List<Object>) SelectProductCategory.get('SIProductCategories');
                system.debug(SIProductCategories);
                String ChosenCategory = (String)((Map<String,Object>) SIProductCategories[0]).get('CategoryName');
                system.debug(ChosenCategory);
                String PreferredNetwork = (String) inputMap.get('PreferredNetwork');
                system.debug(PreferredNetwork);
                Decimal PercentageLowTier = (Decimal) inputMap.get('PercentageLowTier');
                system.debug(PercentageLowTier);
                Decimal PercentageInNetwork = (Decimal) inputMap.get('PercentageInNetwork');
                system.debug(PercentageInNetwork);
                
                List<Id> productIdList = new List<Id>();
                //for(Product2 nP : [SELECT Id FROM Product2 WHERE (vlocity_ins__SubType__c =: ChosenCategory AND vlocity_ins__ProviderNetworkId__c =: PreferredNetwork AND InNetworkThreshold__c <: PercentageInNetwork AND ThresholdLowTier__c < :PercentageLowTier) OR (Name = 'Original Medicare')  LIMIT 50000]){
                for(Product2 nP : [SELECT Id FROM Product2 WHERE (vlocity_ins__SubType__c =: ChosenCategory AND vlocity_ins__ProviderNetworkId__c =: PreferredNetwork) OR (Name = 'Original Medicare')  LIMIT 50000]){
                    productIdList.add(nP.Id);
                }
                system.debug(productIdList);
                productMap = new Map<Id, Product2>([SELECT Id, ProductCode, Name, vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c, vlocity_ins__StandardPremium__c from Product2 WHERE vlocity_ins__SubType__c =:ChosenCategory and Id in :productIdList LIMIT 5000]);
                
                Date productDate = system.today();
                Decimal productPrice = (Decimal)(134.00);
                
                String OriginalMedicareId = '';
                for(Product2 pId : [Select Id from Product2 where Name='Original Medicare' Limit 1]){
                    OriginalMedicareId = pId.Id;
                }
                
                Product2 OriginalProduct = new Product2(Id=OriginalMedicareId, Name='Original Medicare', vlocity_ins__Type__c='Medical', vlocity_ins__EffectiveDate__c=productDate, ProductCode='ORIG-MC', vlocity_ins__StandardPremium__c=productPrice);
                productMap.put(OriginalProduct.Id, OriginalProduct);
            }
            else{
                Map<String, Object> constructEffectiveDate = (Map<String,Object>) inputMap.get('plansPage');
                String EffectiveDateStr = (String)constructEffectiveDate.get('PlanEffectiveDate');
                Date EffectiveDate = Date.parse(EffectiveDateStr);
                system.debug(EffectiveDate);
                productMap = new Map<Id, Product2>([SELECT Id, ProductCode, Name, vlocity_ins__Type__c, vlocity_ins__EffectiveDate__c, vlocity_ins__StandardPremium__c from Product2 WHERE vlocity_ins__Type__c =:searchPlanType AND Description =:searchPlanDescription LIMIT 5000]);
            }

            List<ProductAttributes> productAttributeList=new List<ProductAttributes>();
            system.debug(productMap);
            
            if(productMap!=null&&productMap.size()>0)
            {
                System.debug(' product list '  +productMap);
                Map<Id,List<Attribute>> attributeMap=new Map<Id,List<Attribute>>();
                for(vlocity_ins__AttributeAssignment__c attr:[SELECT Id, Name, vlocity_ins__ObjectId__c,vlocity_ins__ValueDescription__c, vlocity_ins__Value__c, 
                    vlocity_ins__AttributeCategoryId__r.vlocity_ins__DisplaySequence__c, vlocity_ins__ValueDataType__c from vlocity_ins__AttributeAssignment__c where 
                    vlocity_ins__ObjectId__c IN :productMap.keySet() Order by vlocity_ins__ObjectId__c, vlocity_ins__AttributeCategoryId__r.vlocity_ins__DisplaySequence__c 
                     LIMIT 9000]){
                    
                    if(attributeMap.containsKey(attr.vlocity_ins__ObjectId__c))
                        attributeMap.get(attr.vlocity_ins__ObjectId__c).add(new Attribute(attr));
                    else
                        attributeMap.put(attr.vlocity_ins__ObjectId__c,new List<Attribute>{new Attribute(attr)});          
                    
                } 
                
                Integer i = 0;
                system.debug(attributeMap);
                
                for(Id prodId: productMap.keyset()){
                    if(attributeMap.containsKey(prodId)){
                        productAttributeList.add(new ProductAttributes(productMap.get(prodId), attributeMap.get(prodId)));
                    }
                    else{
                        productAttributeList.add(new ProductAttributes(productMap.get(prodId)));
                    }
                    i++;
                }
            }
        system.debug('outputPlanType' + productAttributeList);  
        outMap.put(outputPlanType, productAttributeList);
 
    }
    private class ProductAttributes{
        public string Name;
        public string ProductCode;
        public string Type;
        public string PlanType;
        public string PlanId;
        public Decimal Price;
        public Id ProductId;
        public Date EffectiveDate;
        public List<Attribute> Attributes;
        public ProductAttributes(Product2 prod,List<Attribute> attributes){
            this.name=prod.Name;
            this.Type=prod.vlocity_ins__Type__c;
            this.PlanId=System.Today().year() +  prod.ProductCode;
            this.productCode=prod.ProductCode;
            this.ProductId=prod.Id;
            this.Price=prod.vlocity_ins__StandardPremium__c;
            this.Attributes=attributes;
            this.EffectiveDate=prod.vlocity_ins__EffectiveDate__c;
            
            if(prod.vlocity_ins__EffectiveDate__c != null && System.Today().year() < prod.vlocity_ins__EffectiveDate__c.year()){
                this.PlanType = 'Recommended Plan';
            }
            else{
                this.PlanType = 'Current Plan';
            }
        }
        public ProductAttributes(Product2 prod){
            system.debug(prod);
            this.name=prod.Name;
            this.Type=prod.vlocity_ins__Type__c;
            this.PlanId=System.Today().year() + prod.ProductCode;
            this.productCode=prod.ProductCode;
            this.ProductId=prod.Id;
            this.Price=prod.vlocity_ins__StandardPremium__c;
        }
        
    }
    private class Attribute{
        public string Id;
        public string Description;
        public string Value;
        public string Category;
        public string Name;
        public Decimal CategoryDisplaySequence;
        public Decimal DisplaySequence;
        public string ValueDataType;
        public Attribute(vlocity_ins__AttributeAssignment__c attr){
            this.Id = attr.Id;
            this.Name = attr.Name;
            this.Description = attr.vlocity_ins__ValueDescription__c;
            this.Value = attr.vlocity_ins__Value__c;
            this.CategoryDisplaySequence = attr.vlocity_ins__AttributeCategoryId__r.vlocity_ins__DisplaySequence__c;
            this.DisplaySequence = 1.0;
            this.ValueDataType = attr.vlocity_ins__ValueDataType__c;
        }
    }
    
    public class ContractCode{
      public String contractCode;
      public ContractCode(String contractCode) {
        this.contractCode=contractCode;
      }
    }
    
    public class ProductRate{
      public Decimal Price;
      public String ID;
      public ProductRate(Decimal Price, String ID) {
        this.Price=Price;
        this.ID=ID;
      }
    }
    
}